### ISSUE TITLE
Next Alpha Feature Tracker

### ISSUE THREAD

**Issue by JacksonBurns** [QuantumPioneer/FastLogfileParser#5]
- [x] expose `ALL_FIELDS` to the public API in the same way that `DATA_FIELDS` currently is

**Comment by JacksonBurns** [comment]
- [x] add return types to the info table

**Comment by JacksonBurns** [comment]
- [x] remove unused `e0` regex

**Comment by JacksonBurns** [comment]
Bug fix attached file std_xyz and other fields:
[output.log](https://github.com/QuantumPioneer/FastLogfileParser/files/13492603/output.log)

**Comment by JacksonBurns** [comment]
Lots of copy pasting - try and rewrite the core logic of "open this file, apply this preprocessing, then this search, then this postprocessing" into an abstract function

**Comment by JacksonBurns** [comment]
Add a usage demo for orca (and its corresponding types)

**Comment by JacksonBurns** [comment]
Add parsing of mulliken charges from Gaussian

**Comment by JacksonBurns** [comment]
- [x] parsing of Hirshfeld partial charges
 - [ ] NPA partial charges
 - [ ] NMR shielding constants (istotropic line)
 - [ ] HOMO-LUMO gap, up to some number
 - [ ] multipole moments, up to quadrupole (?)

**Comment by oscarwumit** [comment]
- [ ] electric dipole moment
- [ ] polarizibility

**Comment by hwpang** [comment]
I think we want to parse out the QM descriptors we calculated at `/home/gridsan/hwpang/qmdata_shared/qm_des_hwpang_shihcheng_oscar/output/QM_des_calc` as well
